language: node_js
node_js:
  - "10.16.3"
cache:
  directories:
  - frontend/node_modules
  yarn: true
script:
  - cd frontend/
  - yarn install
  - yarn test
  # Set CI to false to avoid linting errors from stopping build
  - CI=false yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: frontend/build
  on:
    branch: master
